#%RAML 1.0
title: Credit Card System API 
version: v2
baseUri: http://localhost:8083/api/
mediaType: application/json
protocols: [HTTP]




/accounts/{accountId}:
  uriParameters:
    accountId:
      example: ACC003
  get:
    description: Get Details
    displayName: Retrieve accounts
    responses:
      200:
        body:
          application/json:

            