#%RAML 1.0
title: Savings System API 
version: v2
baseUri: http://localhost:8081/api/
mediaType: application/json
protocols: [HTTP]




/accounts/{accountId}:
  uriParameters:
    accountId:
      example: ACC001
  get:
    description: Get Details
    displayName: Retrieve Account Info
    responses:
      200:
        body:
          application/json:
  
            